# -*- coding: utf-8 -*-
"""run.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T2-CIhaNbc7fJ3ar7BZS9EYnIfmehi_y
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

df = pd.read_csv("European_Bank.csv")
df.head()

df.info()
df.describe()
df.isnull().sum()

df.head()
df.info()
df.describe()
df.isnull().sum()
print(df["Exited"].value_counts())

import matplotlib.pyplot as plt

df["Exited"].value_counts().plot(kind="bar")
plt.title("Customer Churn Count")
plt.xlabel("Exited")
plt.ylabel("Number of Customers")
plt.show()

plt.hist(df["Age"], bins=20)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Count")
plt.show()

plt.hist(df["CreditScore"], bins=20)
plt.title("Credit Score Distribution")
plt.xlabel("Credit Score")
plt.ylabel("Count")
plt.show()

import pandas as pd

pd.crosstab(df["Gender"], df["Exited"]).plot(kind="bar")
plt.title("Churn by Gender")
plt.show()

pd.crosstab(df["Geography"], df["Exited"]).plot(kind="bar")
plt.title("Churn by Geography")
plt.show()

import seaborn as sns

plt.figure(figsize=(10,8))
sns.heatmap(df.select_dtypes(include=["number"]).corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

df = df.drop(["CustomerId", "Surname"], axis=1)
df.head()
df = pd.get_dummies(df, columns=["Geography", "Gender"], drop_first=True)
df.head()
df["BalanceSalaryRatio"] = df["Balance"] / (df["EstimatedSalary"] + 1)

df["ProductDensity"] = df["NumOfProducts"] / (df["Age"] + 1)

df["AgeTenureInteraction"] = df["Age"] * df["Tenure"]

df["EngagementScore"] = df["IsActiveMember"] * df["NumOfProducts"]
df.head()
X = df.drop("Exited", axis=1)
y = df["Exited"]
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print("Training Data:", X_train.shape)
print("Testing Data:", X_test.shape)
print("Training Labels:", y_train.shape)
print("Testing Labels:", y_test.shape)

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
lr = LogisticRegression(random_state=42, max_iter=1000)
lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)
gb = GradientBoostingClassifier(random_state=42)
gb.fit(X_train, y_train)

gb_pred = gb.predict(X_test)
from sklearn.metrics import accuracy_score

print("Logistic Regression Accuracy :", accuracy_score(y_test, lr_pred))
print("Decision Tree Accuracy       :", accuracy_score(y_test, dt_pred))
print("Random Forest Accuracy       :", accuracy_score(y_test, rf_pred))
print("Gradient Boosting Accuracy   :", accuracy_score(y_test, gb_pred))
import joblib

joblib.dump(rf, "bank_churn_model.pkl")
joblib.dump(scaler, "scaler.pkl")

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)
y_pred = rf.predict(X_test)
y_prob = rf.predict_proba(X_test)[:, 1]
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob))

import matplotlib.pyplot as plt
import seaborn as sns

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

print(classification_report(y_test, y_pred))

from sklearn.metrics import roc_curve

fpr, tpr, _ = roc_curve(y_test, y_prob)

plt.figure(figsize=(6,4))
plt.plot(fpr, tpr, label="ROC Curve")
plt.plot([0,1], [0,1], linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Get feature importance
importance = rf.feature_importances_

# Get feature names
feature_names = X.columns

# Create DataFrame
feature_importance = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importance
})

# Sort values
feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

print(feature_importance)

plt.figure(figsize=(10,6))

plt.barh(
    feature_importance["Feature"][:10],
    feature_importance["Importance"][:10]
)

plt.title("Top 10 Important Features")
plt.xlabel("Importance Score")
plt.gca().invert_yaxis()
plt.show()

!pip install shap
import shap

# Initialize the SHAP explainer
explainer = shap.TreeExplainer(rf)

shap_values = explainer.shap_values(X_test)
shap.summary_plot(shap_values, X_test, feature_names=X.columns)
shap.summary_plot(
    shap_values,
    X_test,
    feature_names=X.columns,
    plot_type="bar"
)

!pip install streamlit
import streamlit as st
import pandas as pd
import joblib

# Load the trained model and scaler
model = joblib.load("bank_churn_model.pkl")
scaler = joblib.load("scaler.pkl")

st.title("🏦 Bank Customer Churn Prediction")

st.write("Enter the customer details below.")

credit = st.number_input("Credit Score", 300, 900, 650)
age = st.number_input("Age", 18, 100, 35)
tenure = st.number_input("Tenure", 0, 10, 5)
balance = st.number_input("Balance", 0.0, 300000.0, 50000.0)
products = st.number_input("Number of Products", 1, 4, 1)
has_card = st.selectbox("Has Credit Card", [0,1])
active = st.selectbox("Is Active Member", [0,1])
salary = st.number_input("Estimated Salary", 0.0, 300000.0, 50000.0)

gender = st.selectbox("Gender", ["Male","Female"])
geo = st.selectbox("Geography", ["France","Germany","Spain"])

# One-hot encoding
gender_male = 1 if gender=="Male" else 0
geo_germany = 1 if geo=="Germany" else 0
geo_spain = 1 if geo=="Spain" else 0

# Feature Engineering
balance_salary = balance/(salary+1)
product_density = products/(age+1)
age_tenure = age*tenure
engagement = active*products

data = [[
    2025, # Added 'Year' as the first feature
    credit,
    age,
    tenure,
    balance,
    products,
    has_card,
    active,
    salary,
    geo_germany,
    geo_spain,
    gender_male,
    balance_salary,
    product_density,
    age_tenure,
    engagement
]]

data = scaler.transform(data)

if st.button("Predict Churn"):

    prediction = model.predict(data)[0]
    probability = model.predict_proba(data)[0][1]

    if prediction == 1:
        st.error("Customer is likely to Churn")
    else:
        st.success("Customer is likely to Stay")

    st.write(f"Churn Probability: {probability:.2%}")